Kai's initial commit
recursion-teamdev-green/project pull request #8
Opened 2022-08-21 07:15 UTC by jKai-Hw

PersonClassとUserClassを追加しました。

2022-08-21 16:15 UTC, takeshi8989 commented on recursion_capsules.js
> +            let nList = [];
nListはfor文の外で作成すべきです

2022-08-21 16:19 UTC, takeshi8989 requested changes
コメントしてみたので確認よろしくおねがいします！

2022-08-21 23:10 UTC, purin213 commented on recursion_capsules.js
> +            let nList = [];
自分も同じ事思いました↑

2022-08-22 01:49 UTC, jKai-Hw commented on recursion_capsules.js
> +            let nList = [];
マジですみません。直してもう一回プルリクエスト送ります。

2022-08-22 02:18 UTC, jKai-Hw commented
コード修正して再コミットしました。Commitsのところからコード確認できると思いますので、確認お願いします。コメントありがとうございました。

2022-08-22 03:15 UTC, takeshi8989 approved these changes
修正ありがとうございます！完璧です！

2022-08-22 03:16 UTC, merged